// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4Fanl03_2oiRgV2tODvFntOLpqRfxv3s',
    appId: '1:323197978169:web:c1d1eb328e277002266fe8',
    messagingSenderId: '323197978169',
    projectId: 'recipebook-13ab2',
    authDomain: 'recipebook-13ab2.firebaseapp.com',
    storageBucket: 'recipebook-13ab2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFbHbU_PzWbkXK-GD0FwPQRV3LVRPO-E0',
    appId: '1:323197978169:android:3975605140d6f184266fe8',
    messagingSenderId: '323197978169',
    projectId: 'recipebook-13ab2',
    storageBucket: 'recipebook-13ab2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4Fanl03_2oiRgV2tODvFntOLpqRfxv3s',
    appId: '1:323197978169:web:71d2a49ee360afa7266fe8',
    messagingSenderId: '323197978169',
    projectId: 'recipebook-13ab2',
    authDomain: 'recipebook-13ab2.firebaseapp.com',
    storageBucket: 'recipebook-13ab2.firebasestorage.app',
  );

}